### ISSUE TITLE
"commit initiale" should be "commit initial"

### ISSUE THREAD

**Issue by gregkare** [skade/french-people#1]
Commit is masculine in French ("un commit"). I don't think I want to do a pull request to rewrite the initial commit's message though

**Comment by skade** [comment]
Fixed in b891dedc2954965d47cd550c6e14e03dfcc9625e

**Comment by gregkare** [comment]
Thanks a lot for this really quick fix!

![wresting_2](https://cloud.githubusercontent.com/assets/43297/8958762/f73b7840-3606-11e5-8d94-2bb39619e1ec.gif)

**Comment by denis-soundcloud** [comment]
:sparkles: :fr:
